### PR TITLE
Add instructions for reloading dbus

### PR DESCRIPTION
**Pull request by jennydaman**

### CODE REVIEW

**Comment by pali** [comment]
It is really required? I saw that system dbus automatically reload its configuration when it detected that configuration was changed.

Anyway, this step does not work on non-systemd systems. For realoading dbus it is possible to use dbus itself, invoked via dbus-send.

**Comment by jennydaman** [comment]
It seemed to be required for me, though I can do more digging into the details -- this was also the first rule I created under `/etc` i.e. I first had to run `mkdir -p /etc/dbus-1/systemd.d`

**Comment by pali** [comment]
Ok, so maybe it is needed when directory does not exist?

**Comment by pali** [comment]
Are you going to update pull request?

**Comment by jennydaman** [comment]
hey,

So I can reproduce the issue on GDM+GNOME. However on regular startx+plasma, I observe the same behavior as you: dbus policy under `/etc/dbus-1/systemd.d` are applied automatically without a service restart. So it's more likely a quirk of the GNOME stack. I would say it's a problem with GDM so not worth mentioning in your REAADME.

**Comment by pali** [comment]
Ok!

**Pull request closed without merging**
